name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 3
