name: "Deploy Main"

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: mss-boot/mss-boot-frontend/.github/workflows/deploy-cloudflare.yml@main
    with:
      stage: "prod"
    secrets:
      cf_api_token: ${{ secrets.cf_api_token }}
